spring:
  main:
    banner-mode: "off"
  application:
    name: mongo-stream-spark-job
baseFilePath: /zeppelin/k8s-custom
job:
  kafka-bootstrap-servers: kafka.techitalia:9092
  kafka-subscribe-type: subscribe
  mschema: mongo.techitalia
  documents-source:
    kafka-topics: ${job.mschema}.documents
    fs-save-type: parquet
    fs-save-path: ${baseFilePath}/mongo_documents.parquet
    checkpoint-location: /tmp/checkpoint-spark-documents
  internal-documents-source:
    kafka-topics: ${job.mschema}.internaldocuments
    fs-save-type: parquet
    fs-save-path: ${baseFilePath}/mongo_internaldocuments.parquet
    checkpoint-location: /tmp/checkpoint-spark-internaldocuments
spark:
  appname: kafkaDocsToHdfs
  masterUri: local
  homeDir:
  streaming:
    batchDuration: 10000
    kafka:
      params:
        bootstrap-servers: kafka-techitalia:9092
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto.offset.reset: latest
        enable.auto.commit: false
logging:
  level:
    root: INFO
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR
    org.hibernate.tool.hbm2ddl: ERROR
    org.apache.spark: WARN
    org.apache.kafka: WARN
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: ERROR
